version: '3.8'

services:
  db:
    image: postgres:13 
    container_name: pgdb_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mi_basedatos
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyterugr_container
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "9000:8888"
    depends_on:
      - db
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  pgdata:
